import test from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { readdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { servePublic } from '../server.mjs';

/* A retired article must answer 404, not 200.
 *
 * The site is a single-page app: the handler falls back to index.html for any
 * path with no file behind it, and React renders NotFound. That is right for a
 * reader and wrong for a crawler, which is told the page is fine. Eleven
 * articles were live and then retired, and nothing ever said they had gone.
 *
 * These run against the real posts directory rather than a fixture, because the
 * thing under test is precisely whether the server agrees with what the build
 * published, and a fixture would let those two drift apart silently.
 */
const root = fileURLToPath(new URL('..', import.meta.url));
const postsDir = resolve(root, 'src/content/posts');

function listen(handler) {
  return new Promise((res) => {
    const server = createServer((req, r) => void handler(req, r));
    server.listen(0, '127.0.0.1', () => res(server));
  });
}

async function anyPublishedSlug() {
  const names = await readdir(postsDir);
  const md = names.filter((n) => n.endsWith('.md'));
  return md.length ? md[0].slice(0, -3) : null;
}

test('a slug that was never published answers 404', async (context) => {
  if (!existsSync(postsDir)) {
    context.skip('src/content/posts is generated by `npm run sync`');
    return;
  }
  const site = await listen(servePublic);
  context.after(() => site.close());
  const port = site.address().port;

  const gone = await fetch(`http://127.0.0.1:${port}/blog/an-article-that-was-retired`);
  assert.equal(gone.status, 404);
  /* Still the app shell: the reader gets the NotFound page, not a bare string. */
  assert.match(gone.headers.get('content-type') ?? '', /text\/html/);
});

test('a published article still answers 200', async (context) => {
  if (!existsSync(postsDir)) {
    context.skip('src/content/posts is generated by `npm run sync`');
    return;
  }
  const slug = await anyPublishedSlug();
  if (!slug) {
    context.skip('no published articles to check');
    return;
  }
  const site = await listen(servePublic);
  context.after(() => site.close());
  const port = site.address().port;

  const live = await fetch(`http://127.0.0.1:${port}/blog/${slug}`);
  assert.equal(live.status, 200);
});

test('the blog index and unrelated routes are untouched', async (context) => {
  if (!existsSync(postsDir)) {
    context.skip('src/content/posts is generated by `npm run sync`');
    return;
  }
  const site = await listen(servePublic);
  context.after(() => site.close());
  const port = site.address().port;

  /* /blog is a real route with no slug, and a product page is served from a
   * TypeScript module this process never reads. Neither may be 404'd by a check
   * that only knows about articles. */
  for (const path of ['/', '/blog', '/products/aimee', '/products/not-a-product']) {
    const res = await fetch(`http://127.0.0.1:${port}${path}`);
    assert.equal(res.status, 200, `${path} should not be affected`);
  }
});
